//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MIS_VersionM
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MIS_VersionMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MIS_VersionMEntities object using the connection string found in the 'MIS_VersionMEntities' section of the application configuration file.
        /// </summary>
        public MIS_VersionMEntities() : base("name=MIS_VersionMEntities", "MIS_VersionMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MIS_VersionMEntities object.
        /// </summary>
        public MIS_VersionMEntities(string connectionString) : base(connectionString, "MIS_VersionMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MIS_VersionMEntities object.
        /// </summary>
        public MIS_VersionMEntities(EntityConnection connection) : base(connection, "MIS_VersionMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MIS_VersionMModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="eMPID">Initial value of the EMPID property.</param>
        /// <param name="empName">Initial value of the EmpName property.</param>
        public static Employee CreateEmployee(global::System.String eMPID, global::System.String empName)
        {
            Employee employee = new Employee();
            employee.EMPID = eMPID;
            employee.EmpName = empName;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMPID
        {
            get
            {
                return _EMPID;
            }
            set
            {
                if (_EMPID != value)
                {
                    OnEMPIDChanging(value);
                    ReportPropertyChanging("EMPID");
                    _EMPID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EMPID");
                    OnEMPIDChanged();
                }
            }
        }
        private global::System.String _EMPID;
        partial void OnEMPIDChanging(global::System.String value);
        partial void OnEMPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpName
        {
            get
            {
                return _EmpName;
            }
            set
            {
                if (_EmpName != value)
                {
                    OnEmpNameChanging(value);
                    ReportPropertyChanging("EmpName");
                    _EmpName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EmpName");
                    OnEmpNameChanged();
                }
            }
        }
        private global::System.String _EmpName;
        partial void OnEmpNameChanging(global::System.String value);
        partial void OnEmpNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpEmail
        {
            get
            {
                return _EmpEmail;
            }
            set
            {
                OnEmpEmailChanging(value);
                ReportPropertyChanging("EmpEmail");
                _EmpEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmpEmail");
                OnEmpEmailChanged();
            }
        }
        private global::System.String _EmpEmail;
        partial void OnEmpEmailChanging(global::System.String value);
        partial void OnEmpEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpAddress
        {
            get
            {
                return _EmpAddress;
            }
            set
            {
                OnEmpAddressChanging(value);
                ReportPropertyChanging("EmpAddress");
                _EmpAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmpAddress");
                OnEmpAddressChanged();
            }
        }
        private global::System.String _EmpAddress;
        partial void OnEmpAddressChanging(global::System.String value);
        partial void OnEmpAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpPhone
        {
            get
            {
                return _EmpPhone;
            }
            set
            {
                OnEmpPhoneChanging(value);
                ReportPropertyChanging("EmpPhone");
                _EmpPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmpPhone");
                OnEmpPhoneChanged();
            }
        }
        private global::System.String _EmpPhone;
        partial void OnEmpPhoneChanging(global::System.String value);
        partial void OnEmpPhoneChanged();

        #endregion

    
    }

    #endregion

    
}
